SegmentEngine 1.0.0
Factual/segment-analytics-factual-engine-ios pull request #6
Opened 2019-07-12 20:19 UTC by nnlamb25

@weshenderson for review

2019-07-12 20:20 UTC, nnlamb25 commented
For [#3197](https://github.com/Factual/engine/issues/3197)

2019-07-15 22:23 UTC, lispingit requested changes
Looks good -- only a couple minor issues that I found. That said, given the size of this change, make sure this is throughly tested.

2019-07-15 22:23 UTC, weshenderson commented on library/SegmentEngineUserJourneyHandler.m
> +  NSNumber *duration = !startTimestampUnavailable && !endTimestampUnavailable ? @(endTimestamp - startTimestamp) : 0;
The `0` case will result in `nil` rather than `NSNumber` here.

2019-07-15 22:23 UTC, weshenderson commented on example/README.md
> +**(4)** Add your Braze SDK API Key to [Configuration.m](https://github.com/Factual/engine-airship-integration-ios/blob/master/example/UrbanAirshipEngineExample/Configuration.m#L19)
These are Airship links rather than Segment.

2019-07-16 16:00 UTC, lispingit approved these changes

2019-09-10 20:26 UTC, merged